apiVersion: v1
kind: Secret
metadata:
  name: host-operator-secret
type: Opaque
data:
  twilio.account.sid: QUM4MWE4MTcwMTQ5NDU2MmQ3OWFjZmRkNzlkNjhkZTg3Yw==
  twilio.auth.token: NjZlMzllNGUxOTZiMjFlOTM1YzU0OTA4M2RhMGU3NzI=
  twilio.from_number: KzE1MDA1NTUwMDA2